name = "Cardano-Fans/acca"
version = "0.0.4"
licences = ["MIT"]
description = "The Aiken Non Standard Library"
compiler = "v1.1.21"

[repository]
user = "Cardano-Fans"
project = "acca"
platform = "github"
